sudo: required
services:
  - docker

before_install:
  - docker build -t kumarvdocker/multimoduledocker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kumarvdocker/multimoduledocker-test npm run test

after_success:
  - docker build -t kumarvdocker/multimoduledocker-client ./client
  - docker build -t kumarvdocker/multimoduledocker-nginx ./nginx
  - docker build -t kumarvdocker/multimoduledocker-server ./server
  - docker build -t kumarvdocker/multimoduledocker-worker ./worker
  # Login to docker hub
  - echo  "$DOCKER_PASSWORD" | docker login --username $DOCKER_ID --password-stdin
  # send to docker hub
  - docker push kumarvdocker/multimoduledocker-client
  - docker push kumarvdocker/multimoduledocker-nginx
  - docker push kumarvdocker/multimoduledocker-server
  - docker push kumarvdocker/multimoduledocker-worker